version: '3.1'
services:
  db:
    image:  mysql
    restart: always
    command: --secure-file-priv='/var/lib/mysql-files'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
        - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
      - $HOME/Desktop/elections:/var/lib/mysql-files/
volumes:
  my-db: